# Numpy

In [1]:
import numpy as np
np.__version__

'1.18.1'

## builiding blocks

In Python you can build list containing everything

In [5]:
list_numbers = [1,2,3]

In [6]:
list_everything = [1, False, "Some random string"]

numpy requires items of the same type, even if you will put type-wise mismatched elements, it will convert them

In [7]:
np.array([1,2,"1"])

array(['1', '2', '1'], dtype='<U21')

You will always learn type of elements of an array with `dtype`

In [8]:
np.array([1,2,3]).dtype

dtype('int64')

### `array`

In [9]:
classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)

list

In [10]:
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [11]:
numpy_array.shape

(6,)

In [12]:
np.array([2,4]).mean()

3.0

### `matrix`

In [13]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [14]:
numpy_matrix

array([[ 1,  2,  3],
       [ 5,  7, 11]])

### indexing

In [15]:
matrix1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [16]:
matrix1[0, :]

array([1, 2, 3])

In [17]:
matrix1[:, -1]

array([3, 6, 9])

## operations

### axes

In [18]:
matrix2 = np.array([
    [1,2,3],
    [0,8,10],
    [1,10,12]
])

In [19]:
matrix2.sum()

47

In [20]:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [21]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

### typical matrix operations

In [22]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [23]:
np.array([
    [1,2],
    [3,4]
]) + \
np.array([
    [8,9],
    [10,11]
])

array([[ 9, 11],
       [13, 15]])

In [24]:
np.array([
    [1,2],
    [3,4]
]).dot([1,1])

array([3, 7])